Support modified video files for OSD overlay
fpv-wtf/wtfos-configurator pull request #394
Opened 2023-07-13 18:59 UTC by FinalFrag

Currently the OSD overlay feature only supports video files that come straight from the goggles. This PR adds support for modifications as long as they don't change the video length.

Technical: video files straight from the goggles have all frames in the correct order. Tools like gyroflow or superviou save frames in a different order that they are supposed to be shown. The correct order is described in the optional ctts box in the mp4 spec.

An example of footage that has the aspect ratio altered with superviou:
![image](https://github.com/fpv-wtf/wtfos-configurator/assets/16101005/bbd2c689-5b5b-44be-90b7-9fc642d5a511)

2023-07-13 19:06 UTC, stylesuxx commented
Cool - thank you!

Just an FYI: you only need to add/update the en translation, crowdin will do the rest.

2023-07-13 19:16 UTC, stylesuxx requested changes
Looking good, only some semicolons are missing.

2023-07-13 19:16 UTC, stylesuxx commented on src/osd-overlay/processor.ts
> +          frame = ctts.sampleCounts.slice(0, j).reduce((acc, e) => acc + e, 0)
Semicolon missing.

2023-07-13 19:16 UTC, stylesuxx commented on src/osd-overlay/processor.ts
> +      const initialOffset = ctts.sampleOffsets[0] / sampleDelta
Semicolon missing.

2023-07-13 19:16 UTC, stylesuxx commented on src/osd-overlay/processor.ts
> +      lastSampleIndex += sampleChunks.length
Semicolon missing.

2023-07-13 19:16 UTC, stylesuxx commented on src/osd-overlay/processor.ts
> +    const orderedFrames = []
Semicolon missing.

2023-07-13 19:16 UTC, stylesuxx commented on src/osd-overlay/processor.ts
> +        orderedFrames.push(this.decodedFrames[lastSampleIndex + i])
Semicolon missing.

2023-07-13 19:17 UTC, j005u commented
@FinalFrag I should add that if you want to get your hands dirty with C, then msp-osd on the goggles side could be improved to add (roughly estimated) timestamps per frame so that the .osd could also be applied to air side recordings/gopro footage.

The trouble with trying to do that with the current frame index like we handle goggles side DVR is that any frames that get skipped due to transmission issues push things out of sync. This de-sync can build up significantly over longer flight videos.

Just mentioning it FYI. In any case your improvements are really appreciated!

2023-07-13 20:55 UTC, FinalFrag commented
Bet you can't tell I'm used to a non-semicolon environment :P

Isn't it weird ESlint didn't fail on this?

2023-07-13 21:07 UTC, FinalFrag commented
@j005u Took a quick look at the msp-osd code, but that is way beyond me :)

2023-07-13 21:43 UTC, j005u commented
> @j005u Took a quick look at the msp-osd code, but that is way beyond me :)

The .osd writing code is actually extremely straight forward: https://github.com/fpv-wtf/msp-osd/blob/03c1faf4fe808548f6a737a43231c24049403988/jni/rec/rec.c#L74C21-L74C21

If you'd be interested in dealing with the rendering code then I'm sure someone on the team can add a milliseconds from frame 0 count to each frames header.

2023-07-13 21:45 UTC, stylesuxx commented
> Isn't it weird ESlint didn't fail on this?

Yeah, I was wondering too - need to double check the config.

2023-07-13 21:47 UTC, stylesuxx approved these changes
Awesome, looking good - thank you!

Since you are on such a roll with the Overlay related stuff, maybe I can interest you in some of the [open issues](https://github.com/fpv-wtf/wtfos-configurator/issues?q=is%3Aissue+is%3Aopen+label%3Aoverlay) ;-)

2023-07-14 11:10 UTC, merged

2023-07-14 11:10 UTC, stylesuxx commented
Merged. Thanks again for you contribution, very much appreciated!