Switch to using new png fonts + .osd file format v2 support:
fpv-wtf/wtfos-configurator pull request #420
Opened 2024-05-15 21:22 UTC by benlumley

- Use PNG font files instead of the old bin format
- Only 2 fonts now; one for sd + one for hd, rather than separate pages
- But the PNG can have equivalent of 4 pages; so BF 4.5 colour is supported
- OSD v2 support; which uses a 4 char string (BTFL/INAV etc) as the FC identifier. Can still handle v1 files too.
- Font files now optional; it will use the FC variant to load defaults from the msp-osd repo.

2024-05-15 21:31 UTC, benlumley commented
(corresponds with upcoming msp-osd 0.12.x)

2024-05-15 21:41 UTC, stylesuxx commented on src/osd-overlay/osd.ts
> +
Unnecessary empty line.

2024-05-15 21:43 UTC, stylesuxx requested changes
Just one nit picky comment, otherwise everything looks fine to me.

2024-05-16 11:03 UTC, stylesuxx approved these changes

2024-05-16 11:04 UTC, merged

2024-05-16 11:05 UTC, benlumley commented
thanks @stylesuxx